// apps/web/src/pages/AiAssistantPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { Badge, Button, FormControl } from "frappe-ui";

import {
  cancelAIProposal,
  confirmAIProposal,
  createAIConversation,
  fetchAIConversation,
  listAIConversations,
  sendAIConversationMessage,
  updateAIConversation,
} from "../api/client";
import AppShell from "../components/AppShell.vue";
import { authToken } from "../composables/useAuth";
import type { AIConversation, AIMessage, AIProposal, AIResponse } from "../types/domain";
import { dateText, labelize } from "../utils/format";

const route = useRoute();
const conversations = ref<AIConversation[]>([]);
const active = ref<AIConversation | null>(null);
const prompt = ref("");
const loading = ref(false);
const sending = ref(false);
const error = ref("");

const projectContext = computed(() => ({
  project_id: route.query.projectId ? String(route.query.projectId) : undefined,
  project_code: route.query.projectCode ? String(route.query.projectCode) : undefined,
}));

onMounted(load);

async function load() {
  loading.value = true;
  error.value = "";
  try {
    conversations.value = await listAIConversations(authToken());
    const context = projectContext.value;
    const contextual = context.project_id ? conversations.value.find((item) => item.projectId === context.project_id) : null;
    if (contextual) {
      await openConversation(contextual.id);
    } else if (context.project_id || conversations.value.length === 0) {
      await newConversation();
    } else {
      await openConversation(conversations.value[0].id);
    }
  } catch (cause) {
    error.value = cause instanceof Error ? cause.message : "Unable to load AI history.";
  } finally {
    loading.value = false;
  }
}

async function newConversation() {
  active.value = await createAIConversation(authToken(), {
    title: projectContext.value.project_code ? `Project ${projectContext.value.project_code}` : undefined,
    ...projectContext.value,
  });
  conversations.value = await listAIConversations(authToken());
}

async function openConversation(id: string) {
  active.value = await fetchAIConversation(authToken(), id);
}

async function archiveConversation(id: string) {
  await updateAIConversation(authToken(), id, { archived: true });
  active.value = null;
  await load();
}

async function send() {
  const text = prompt.value.trim();
  if (!text || !active.value) return;
  sending.value = true;
  error.value = "";
  try {
    const result = await sendAIConversationMessage(authToken(), active.value.id, text);
    active.value = result.conversation;
    prompt.value = "";
    conversations.value = await listAIConversations(authToken());
  } catch (cause) {
    error.value = cause instanceof Error ? cause.message : "Unable to send message.";
  } finally {
    sending.value = false;
  }
}

async function proposalAction(proposal: AIProposal, action: "confirm" | "cancel") {
  sending.value = true;
  try {
    const response = action === "confirm" ? await confirmAIProposal(authToken(), proposal.id) : await cancelAIProposal(authToken(), proposal.id);
    const current = active.value;
    if (current) {
      current.messages = [
        ...(current.messages ?? []),
        {
          id: `local-${Date.now()}`,
          conversationId: current.id,
          role: "assistant",
          content: response.message,
          responseKind: response.kind,
          metadata: response,
        },
      ];
    }
  } finally {
    sending.value = false;
  }
}

function proposalFromMessage(message: AIMessage): AIProposal | null {
  const metadata = message.metadata as AIResponse | undefined;
  return metadata?.proposal ?? null;
}
</script>

<template>
  <AppShell>
    <div class="grid min-h-[calc(100vh-8rem)] gap-5 xl:grid-cols-[320px_1fr]">
      <aside class="border border-line bg-panel">
        <div class="flex items-center justify-between border-b border-line px-4 py-3">
          <h1 class="text-base font-semibold">AI history</h1>
          <Button icon="plus" @click="newConversation" />
        </div>
        <div class="divide-y divide-line">
          <button
            v-for="conversation in conversations"
            :key="conversation.id"
            type="button"
            class="block w-full px-4 py-3 text-left text-sm hover:bg-gray-50"
            :class="{ 'bg-gray-50': active?.id === conversation.id }"
            @click="openConversation(conversation.id)"
          >
            <span class="block truncate font-medium">{{ conversation.title }}</span>
            <span class="block text-xs text-muted">{{ conversation.projectCode || 'General' }} · {{ dateText(conversation.updatedAt) }}</span>
          </button>
          <div v-if="!loading && conversations.length === 0" class="px-4 py-8 text-center text-sm text-muted">No conversations</div>
        </div>
      </aside>

      <section class="flex min-h-0 flex-col border border-line bg-panel">
        <div class="flex flex-wrap items-start justify-between gap-3 border-b border-line px-4 py-3">
          <div>
            <h2 class="text-lg font-semibold">{{ active?.title || 'New conversation' }}</h2>
            <p class="mt-1 text-sm text-muted">{{ active?.projectCode ? `Project ${active.projectCode}` : 'General fund operations' }}</p>
          </div>
          <Button v-if="active" label="Archive" icon-left="archive" @click="archiveConversation(active.id)" />
        </div>

        <div v-if="error" class="m-4 border border-danger/30 bg-red-50 px-3 py-2 text-sm text-danger">{{ error }}</div>

        <div class="min-h-0 flex-1 space-y-4 overflow-y-auto p-4">
          <article v-for="message in active?.messages || []" :key="message.id" class="max-w-4xl border border-line p-4" :class="message.role === 'user' ? 'ml-auto bg-gray-50' : 'bg-panel'">
            <div class="mb-2 flex items-center justify-between gap-3">
              <Badge :label="message.role === 'user' ? 'You' : 'TrancheAI'" />
              <span class="text-xs text-muted">{{ dateText(message.createdAt) }}</span>
            </div>
            <p class="whitespace-pre-wrap text-sm leading-6">{{ message.content }}</p>

            <div v-if="proposalFromMessage(message)" class="mt-4 border border-line bg-gray-50 p-3 text-sm">
              <div class="flex flex-wrap items-center justify-between gap-2">
                <div>
                  <div class="font-medium">{{ labelize(proposalFromMessage(message)?.action) }}</div>
                  <div class="text-muted">Status: {{ labelize(proposalFromMessage(message)?.status) }}</div>
                </div>
                <div class="flex gap-2">
                  <Button label="Cancel" icon-left="x" @click="proposalAction(proposalFromMessage(message)!, 'cancel')" />
                  <Button variant="solid" label="Confirm" icon-left="check" @click="proposalAction(proposalFromMessage(message)!, 'confirm')" />
                </div>
              </div>
              <pre class="mt-3 max-h-60 overflow-auto bg-white p-3 text-xs">{{ JSON.stringify(proposalFromMessage(message)?.proposedValues, null, 2) }}</pre>
            </div>
          </article>

          <div v-if="!loading && (!active || !active.messages?.length)" class="grid h-full place-items-center text-center text-sm text-muted">
            <div>
              <div class="text-base font-medium text-foreground">Start with a project or workflow question</div>
              <p class="mt-1">The full thread is stored in the TrancheAI database.</p>
            </div>
          </div>
        </div>

        <form class="border-t border-line p-4" @submit.prevent="send">
          <div class="grid gap-3 md:grid-cols-[1fr_auto]">
            <FormControl v-model="prompt" type="textarea" placeholder="Ask about a project, create a proposal, or request a reconciliation explanation" />
            <Button variant="solid" type="submit" label="Send" icon-left="send" :disabled="!active" :loading="sending" />
          </div>
        </form>
      </section>
    </div>
  </AppShell>
</template>

// apps/web/src/pages/AiAssistantPage.tsx
import { AlertTriangle, Bot, Check, Download, FileText, Loader2, Send, X } from "lucide-react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import type { FormEvent } from "react";
import { useSearchParams } from "react-router-dom";
import { cancelAIProposal, confirmAIProposal, downloadFile, sendAIRequest } from "../api/client";
import type { AIProposal, AIResponse } from "../api/client";
import { useToken } from "../app/AuthContext";

interface Message {
  id: string;
  role: "user" | "assistant";
  text: string;
  response?: AIResponse;
}

const fallbackSuggestions = [
  "Find projects related to robotics",
  "List reconciliation issues",
  "Generate project master export",
];

export function AiAssistantPage() {
  const token = useToken();
  const queryClient = useQueryClient();
  const [searchParams] = useSearchParams();
  const projectId = searchParams.get("projectId") ?? undefined;
  const projectCode = searchParams.get("projectCode") ?? undefined;
  const suggestions = useMemo(() => (projectCode ? [`Summarize ${projectCode}`, `Show financial summary for ${projectCode}`, `Create a draft tranche of INR 50000 for ${projectCode}`] : fallbackSuggestions), [projectCode]);
  const [prompt, setPrompt] = useState("");
  const [messages, setMessages] = useState<Message[]>([]);
  const [activeProposal, setActiveProposal] = useState<AIProposal | null>(null);

  const ask = useMutation({
    mutationFn: (text: string) => sendAIRequest(token, { text, current_project_id: projectId, current_project_code: projectCode }),
    onSuccess: (response) => {
      setMessages((items) => [...items, { id: uniqueId("assistant"), role: "assistant", text: response.message, response }]);
      if (response.proposal) setActiveProposal(response.proposal);
    },
    onError: (error) => {
      setMessages((items) => [...items, { id: uniqueId("assistant"), role: "assistant", text: error instanceof Error ? error.message : "AI request failed.", response: { kind: "error", message: "AI request failed." } }]);
    },
  });

  const confirm = useMutation({
    mutationFn: () => {
      if (!activeProposal) throw new Error("No proposal selected.");
      return confirmAIProposal(token, activeProposal.id);
    },
    onSuccess: (response) => {
      if (response.proposal) setActiveProposal(response.proposal);
      setMessages((items) => [...items, { id: uniqueId("assistant"), role: "assistant", text: response.message, response }]);
      queryClient.invalidateQueries({ queryKey: ["projects"] });
      queryClient.invalidateQueries({ queryKey: ["reconciliation"] });
    },
  });

  const cancel = useMutation({
    mutationFn: () => {
      if (!activeProposal) throw new Error("No proposal selected.");
      return cancelAIProposal(token, activeProposal.id);
    },
    onSuccess: (response) => {
      if (response.proposal) setActiveProposal(response.proposal);
      setMessages((items) => [...items, { id: uniqueId("assistant"), role: "assistant", text: response.message, response }]);
    },
  });

  const download = useMutation({
    mutationFn: (path: string) => downloadFile(token, path, path.split("/").pop() ?? "trancheai-export.csv"),
  });

  function submit(event: FormEvent) {
    event.preventDefault();
    const text = prompt.trim();
    if (!text || ask.isPending) return;
    setMessages((items) => [...items, { id: uniqueId("user"), role: "user", text }]);
    setPrompt("");
    ask.mutate(text);
  }

  const pendingProposal = activeProposal?.status === "pending_confirmation";

  return (
    <div className="space-y-5">
      <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
        <div>
          <p className="text-sm text-muted">AI Assistant</p>
          <h1 className="text-2xl font-semibold">TrancheAI workflow assistant</h1>
        </div>
        {projectCode ? (
          <div className="inline-flex w-fit items-center gap-2 rounded-md border border-line bg-panel px-3 py-2 text-sm">
            <FileText className="h-4 w-4 text-accent" />
            <span>{projectCode}</span>
          </div>
        ) : null}
      </div>

      <div className="grid min-h-[680px] gap-4 xl:grid-cols-[minmax(0,1fr)_390px]">
        <section className="flex min-h-[560px] flex-col rounded-md border border-line bg-panel">
          <div className="border-b border-line px-4 py-3">
            <div className="flex items-center gap-2 text-sm font-semibold">
              <Bot className="h-4 w-4 text-accent" />
              Assistant thread
            </div>
          </div>

          <div className="flex-1 space-y-3 overflow-y-auto px-4 py-4">
            {messages.length === 0 ? (
              <div className="rounded-md border border-dashed border-line bg-surface p-5 text-sm text-muted">No messages yet.</div>
            ) : null}
            {messages.map((message) => (
              <article key={message.id} className={`max-w-[88%] rounded-md border p-3 text-sm ${message.role === "user" ? "ml-auto border-accent bg-surface" : "border-line bg-surface"}`}>
                <div className="mb-1 text-xs font-medium uppercase tracking-normal text-muted">{message.role === "user" ? "You" : "Assistant"}</div>
                <p className="whitespace-pre-wrap break-words">{message.text}</p>
                {message.response?.data ? <DataBlock data={message.response.data} /> : null}
                {message.response?.download_url ? (
                  <button className="focus-ring mt-3 inline-flex items-center gap-2 rounded-md border border-line px-3 py-2 text-xs font-medium" onClick={() => download.mutate(message.response?.download_url ?? "")} disabled={download.isPending}>
                    <Download className="h-4 w-4" />
                    Download export
                  </button>
                ) : null}
              </article>
            ))}
            {ask.isPending ? (
              <div className="inline-flex items-center gap-2 rounded-md border border-line bg-surface px-3 py-2 text-sm text-muted">
                <Loader2 className="h-4 w-4 animate-spin" />
                Working
              </div>
            ) : null}
          </div>

          <div className="border-t border-line p-4">
            <div className="mb-3 flex flex-wrap gap-2">
              {suggestions.map((item) => (
                <button key={item} className="focus-ring rounded-md border border-line bg-surface px-3 py-1.5 text-xs hover:border-accent" onClick={() => setPrompt(item)} type="button">
                  {item}
                </button>
              ))}
            </div>
            <form className="flex gap-2" onSubmit={submit}>
              <textarea
                className="focus-ring min-h-16 flex-1 resize-none rounded-md border border-line bg-surface px-3 py-2 text-sm"
                aria-label="AI request"
                value={prompt}
                onChange={(event) => setPrompt(event.target.value)}
              />
              <button className="focus-ring inline-flex h-16 w-16 shrink-0 items-center justify-center rounded-md bg-accent text-surface disabled:opacity-55" aria-label="Send AI request" disabled={ask.isPending || !prompt.trim()}>
                {ask.isPending ? <Loader2 className="h-5 w-5 animate-spin" /> : <Send className="h-5 w-5" />}
              </button>
            </form>
          </div>
        </section>

        <aside className="space-y-4">
          <ProposalPanel proposal={activeProposal} onConfirm={() => confirm.mutate()} onCancel={() => cancel.mutate()} confirmBusy={confirm.isPending} cancelBusy={cancel.isPending} canAct={Boolean(pendingProposal)} />
          {(confirm.error || cancel.error || download.error) ? (
            <div className="rounded-md border border-danger bg-panel p-3 text-sm text-danger">Action failed. Refresh the proposal and check role permissions.</div>
          ) : null}
        </aside>
      </div>
    </div>
  );
}

function ProposalPanel({ proposal, onConfirm, onCancel, confirmBusy, cancelBusy, canAct }: { proposal: AIProposal | null; onConfirm: () => void; onCancel: () => void; confirmBusy: boolean; cancelBusy: boolean; canAct: boolean }) {
  if (!proposal) {
    return (
      <section className="rounded-md border border-line bg-panel p-4">
        <div className="flex items-center gap-2 text-sm font-semibold">
          <Check className="h-4 w-4 text-accent" />
          Proposal review
        </div>
        <div className="mt-4 rounded-md border border-dashed border-line bg-surface p-4 text-sm text-muted">No active proposal.</div>
      </section>
    );
  }
  const warnings = proposal.validationResult?.warnings ?? [];
  const errors = proposal.validationResult?.errors ?? [];
  return (
    <section className="rounded-md border border-line bg-panel p-4">
      <div className="flex items-start justify-between gap-3">
        <div>
          <div className="text-sm font-semibold">Proposal review</div>
          <div className="mt-1 text-xs text-muted">{proposal.action.replace(/_/g, " ")}</div>
        </div>
        <span className={`rounded-md border px-2 py-1 text-xs ${statusClass(proposal.status)}`}>{proposal.status.replace(/_/g, " ")}</span>
      </div>

      <div className="mt-4 space-y-4 text-sm">
        <KeyValueList title="Current values" values={proposal.currentValues} empty="No existing record." />
        <KeyValueList title="Proposed values" values={proposal.proposedValues} empty="No proposed values." />
        {warnings.length ? <Notice tone="warning" items={warnings} /> : null}
        {errors.length ? <Notice tone="danger" items={errors} /> : null}
        {proposal.expiresAt ? <div className="text-xs text-muted">Expires {new Date(proposal.expiresAt).toLocaleString()}</div> : null}
      </div>

      <div className="mt-4 grid grid-cols-2 gap-2">
        <button className="focus-ring inline-flex h-10 items-center justify-center gap-2 rounded-md border border-line bg-surface text-sm font-medium disabled:opacity-55" onClick={onCancel} disabled={!canAct || cancelBusy}>
          {cancelBusy ? <Loader2 className="h-4 w-4 animate-spin" /> : <X className="h-4 w-4" />}
          Cancel
        </button>
        <button className="focus-ring inline-flex h-10 items-center justify-center gap-2 rounded-md bg-accent text-sm font-medium text-surface disabled:opacity-55" onClick={onConfirm} disabled={!canAct || confirmBusy}>
          {confirmBusy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}
          Confirm
        </button>
      </div>
    </section>
  );
}

function DataBlock({ data }: { data: AIResponse["data"] }) {
  if (!data) return null;
  if (Array.isArray(data)) {
    if (!data.length) return <div className="mt-3 text-xs text-muted">No rows.</div>;
    const keys = Array.from(new Set(data.flatMap((row) => Object.keys(row)))).slice(0, 6);
    return (
      <div className="mt-3 overflow-x-auto rounded-md border border-line">
        <table className="min-w-full text-left text-xs">
          <thead className="bg-panel text-muted">
            <tr>
              {keys.map((key) => <th className="px-2 py-1.5 font-medium" key={key}>{formatKey(key)}</th>)}
            </tr>
          </thead>
          <tbody className="divide-y divide-line">
            {data.slice(0, 8).map((row, index) => (
              <tr key={index}>
                {keys.map((key) => <td className="max-w-56 break-words px-2 py-1.5" key={key}>{formatValue(row[key])}</td>)}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  }
  return <KeyValueList title="Result" values={data} />;
}

function KeyValueList({ title, values, empty = "No values." }: { title: string; values: Record<string, unknown>; empty?: string }) {
  const entries = Object.entries(values ?? {});
  return (
    <div>
      <div className="mb-2 text-xs font-medium uppercase tracking-normal text-muted">{title}</div>
      {entries.length === 0 ? <div className="rounded-md border border-line bg-surface px-3 py-2 text-sm text-muted">{empty}</div> : null}
      {entries.length > 0 ? <div className="divide-y divide-line rounded-md border border-line bg-surface">
        {entries.map(([key, value]) => (
          <div key={key} className="grid gap-2 px-3 py-2 sm:grid-cols-[140px_minmax(0,1fr)]">
            <span className="text-xs text-muted">{formatKey(key)}</span>
            <span className="break-words text-sm">{formatValue(value)}</span>
          </div>
        ))}
      </div> : null}
    </div>
  );
}

function Notice({ tone, items }: { tone: "warning" | "danger"; items: string[] }) {
  const toneClass = tone === "warning" ? "border-warning text-warning" : "border-danger text-danger";
  return (
    <div className={`rounded-md border bg-surface p-3 text-sm ${toneClass}`}>
      <div className="mb-2 flex items-center gap-2 font-medium">
        <AlertTriangle className="h-4 w-4" />
        {tone === "warning" ? "Warnings" : "Errors"}
      </div>
      <ul className="list-disc space-y-1 pl-5">
        {items.map((item) => <li key={item}>{item}</li>)}
      </ul>
    </div>
  );
}

function statusClass(status: string) {
  if (status === "executed") return "border-success text-success";
  if (status === "failed" || status === "expired") return "border-danger text-danger";
  if (status === "cancelled") return "border-muted text-muted";
  return "border-warning text-warning";
}

function formatKey(key: string) {
  return key.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/_/g, " ");
}

function formatValue(value: unknown): string {
  if (value === null || value === undefined || value === "") return "-";
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

function uniqueId(prefix: string) {
  return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}
