// apps/web/src/pages/ImportsExportsPage.tsx
import { Download, FileUp, TableProperties, Upload } from "lucide-react";
import { useState } from "react";
import { commitImport, downloadFile, previewImport } from "../api/client";
import type { ImportBatch } from "../api/client";
import { useToken } from "../app/AuthContext";
import { Button } from "../components/Button";
import { PageHeader } from "./DashboardPage";

const templates = [
  { label: "Projects", type: "projects" },
  { label: "Funding Sanctions", type: "funding_sanctions" },
  { label: "Funding Revisions", type: "funding_revisions" },
  { label: "Tranches", type: "tranches" },
];
const exports = ["Project Master CSV", "Project Master XLSX", "Tranche Register CSV", "Tranche Register XLSX"];

export function ImportsExportsPage() {
  const token = useToken();
  const [importType, setImportType] = useState("projects");
  const [file, setFile] = useState<File | null>(null);
  const [batch, setBatch] = useState<ImportBatch | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<"preview" | "commit" | null>(null);

  async function handlePreview() {
    if (!file) {
      setError("Select a CSV file first.");
      return;
    }
    setBusy("preview");
    setError(null);
    try {
      setBatch(await previewImport(token, importType, file));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Import preview failed.");
    } finally {
      setBusy(null);
    }
  }

  async function handleCommit() {
    if (!batch) return;
    setBusy("commit");
    setError(null);
    try {
      setBatch(await commitImport(token, batch.id));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Import commit failed.");
    } finally {
      setBusy(null);
    }
  }

  const canCommit = Boolean(batch && batch.proposedCreates > 0 && batch.failedRows === 0 && batch.status === "previewed");
  return (
    <section className="space-y-6">
      <PageHeader title="Imports and Exports" description="Canonical templates prevent spreadsheet columns from becoming the database design." />
      <div className="grid gap-5 xl:grid-cols-2">
        <section className="rounded-lg border border-border bg-[oklch(99%_0.004_250)]">
          <div className="border-b border-border px-4 py-3 text-sm font-semibold">Import Templates</div>
          <div className="divide-y divide-border">
            {templates.map((item) => (
              <div key={item.type} className="flex items-center justify-between gap-4 px-4 py-3">
                <div className="flex items-center gap-3 text-sm"><FileUp className="h-4 w-4 text-primary" />{item.label}</div>
                <Button onClick={() => downloadFile(token, `/api/v1/imports/templates/${item.type}.csv`, `${item.type.replace(/_/g, "-")}.csv`)}>Download CSV</Button>
              </div>
            ))}
          </div>
        </section>
        <section className="rounded-lg border border-border bg-[oklch(99%_0.004_250)]">
          <div className="border-b border-border px-4 py-3 text-sm font-semibold">Exports</div>
          <div className="divide-y divide-border">
            {exports.map((name) => (
              <div key={name} className="flex items-center justify-between gap-4 px-4 py-3">
                <div className="flex items-center gap-3 text-sm"><TableProperties className="h-4 w-4 text-primary" />{name}</div>
                <Button onClick={() => downloadFile(token, exportPath(name), `${name.toLowerCase().replace(/ /g, "-")}.${name.includes("XLSX") ? "xlsx" : "csv"}`)}><Download className="h-4 w-4" />Generate</Button>
              </div>
            ))}
          </div>
        </section>
      </div>
      <section className="rounded-lg border border-border bg-[oklch(99%_0.004_250)] p-4">
        <div className="text-sm font-semibold">Import Review</div>
        <div className="mt-3 grid gap-3 md:grid-cols-[220px_1fr_auto_auto] md:items-end">
          <label className="block text-sm font-medium" htmlFor="importType">
            Import Type
            <select id="importType" className="focus-ring mt-1 w-full rounded-md border border-line bg-surface px-3 py-2 text-sm" value={importType} onChange={(event) => { setImportType(event.target.value); setBatch(null); }}>
              {templates.map((item) => <option key={item.type} value={item.type}>{item.label}</option>)}
            </select>
          </label>
          <label className="block text-sm font-medium" htmlFor="importFile">
            CSV File
            <input id="importFile" className="focus-ring mt-1 w-full rounded-md border border-line bg-surface px-3 py-2 text-sm" type="file" accept=".csv,text/csv" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setBatch(null); }} />
          </label>
          <Button onClick={handlePreview} disabled={busy !== null}><Upload className="h-4 w-4" />{busy === "preview" ? "Previewing" : "Preview"}</Button>
          <Button onClick={handleCommit} disabled={!canCommit || busy !== null}>{busy === "commit" ? "Committing" : "Commit"}</Button>
        </div>
        {error ? <div className="mt-3 rounded-md border border-danger bg-surface px-3 py-2 text-sm text-danger">{error}</div> : null}
        {batch ? <ImportPreview batch={batch} /> : <div className="mt-3 rounded-md border border-dashed border-border p-8 text-center text-sm text-[oklch(45%_0.014_250)]">Preview a canonical CSV before committing records.</div>}
      </section>
    </section>
  );
}

function ImportPreview({ batch }: { batch: ImportBatch }) {
  const metrics = [
    ["Rows", batch.rowsDetected],
    ["Valid", batch.validRows],
    ["Invalid", batch.invalidRows],
    ["Duplicates", batch.duplicateRows],
    ["Existing", batch.existingRecordsMatched],
    ["Creates", batch.proposedCreates],
    ["Committed", batch.committedRows],
    ["Failed", batch.failedRows],
  ];
  return (
    <div className="mt-4 space-y-4">
      <div className="grid gap-2 sm:grid-cols-4 xl:grid-cols-8">
        {metrics.map(([label, value]) => (
          <div key={label} className="border-y border-line py-2">
            <div className="text-xs text-muted">{label}</div>
            <div className="text-lg font-semibold">{value}</div>
          </div>
        ))}
      </div>
      <div className="overflow-x-auto rounded-md border border-line">
        <table className="min-w-[960px] w-full text-left text-sm">
          <thead className="bg-surface text-xs uppercase text-muted">
            <tr>
              <th className="px-3 py-2">Row</th>
              <th className="px-3 py-2">Status</th>
              <th className="px-3 py-2">Action</th>
              <th className="px-3 py-2">Project</th>
              <th className="px-3 py-2">Messages</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-line">
            {batch.rows.map((row) => (
              <tr key={row.id}>
                <td className="px-3 py-2">{row.rowNumber}</td>
                <td className="px-3 py-2"><span className={statusClass(row.status)}>{row.status}</span></td>
                <td className="px-3 py-2">{row.proposedAction}</td>
                <td className="px-3 py-2">{String(row.normalizedValues.project_code ?? "")}</td>
                <td className="px-3 py-2">
                  {[...row.errors, ...row.warnings].length ? [...row.errors, ...row.warnings].join(" ") : "Ready"}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function statusClass(status: string) {
  const base = "inline-flex rounded px-2 py-1 text-xs font-medium";
  if (status === "valid" || status === "committed") return `${base} bg-[oklch(94%_0.025_150)] text-[oklch(34%_0.09_150)]`;
  if (status === "invalid" || status === "failed") return `${base} bg-[oklch(94%_0.035_25)] text-danger`;
  return `${base} bg-muted text-[oklch(38%_0.012_250)]`;
}

function exportPath(name: string) {
  if (name === "Project Master CSV") return "/api/v1/exports/project-master.csv";
  if (name === "Project Master XLSX") return "/api/v1/exports/project-master.xlsx";
  if (name === "Tranche Register CSV") return "/api/v1/exports/tranche-register.csv";
  if (name === "Tranche Register XLSX") return "/api/v1/exports/tranche-register.xlsx";
  return "/api/v1/exports/project-master.csv";
}

// apps/web/src/pages/ImportsExportsPage.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { Badge, Button, FormControl } from "frappe-ui";

import { commitImport, downloadFile, previewImport } from "../api/client";
import AppShell from "../components/AppShell.vue";
import StatTile from "../components/StatTile.vue";
import { authToken } from "../composables/useAuth";
import type { ImportBatch } from "../types/domain";
import { labelize } from "../utils/format";

const importType = ref("projects");
const selectedFile = ref<File | null>(null);
const batch = ref<ImportBatch | null>(null);
const loading = ref(false);
const error = ref("");

const rows = computed(() => batch.value?.rows ?? []);

async function preview() {
  if (!selectedFile.value) {
    error.value = "Choose a CSV file first.";
    return;
  }
  loading.value = true;
  error.value = "";
  try {
    batch.value = await previewImport(authToken(), importType.value, selectedFile.value);
  } catch (cause) {
    error.value = cause instanceof Error ? cause.message : "Unable to preview import.";
  } finally {
    loading.value = false;
  }
}

async function commit() {
  if (!batch.value) return;
  loading.value = true;
  error.value = "";
  try {
    batch.value = await commitImport(authToken(), batch.value.id);
  } catch (cause) {
    error.value = cause instanceof Error ? cause.message : "Unable to commit import.";
  } finally {
    loading.value = false;
  }
}

function chooseFile(event: Event) {
  selectedFile.value = (event.target as HTMLInputElement).files?.[0] ?? null;
}

function exportFile(path: string, filename: string) {
  return downloadFile(authToken(), path, filename);
}
</script>

<template>
  <AppShell>
    <div>
      <h1 class="text-2xl font-semibold">Imports / Exports</h1>
      <p class="mt-1 text-sm text-muted">Preview, validate and commit project funding data without bypassing workflow controls.</p>
    </div>

    <div v-if="error" class="mt-4 border border-danger/30 bg-red-50 px-3 py-2 text-sm text-danger">{{ error }}</div>

    <div class="mt-5 grid gap-5 xl:grid-cols-[1.15fr_0.85fr]">
      <section class="border border-line bg-panel p-4">
        <h2 class="text-base font-semibold">CSV import</h2>
        <div class="mt-4 grid gap-3 md:grid-cols-[220px_1fr_auto_auto]">
          <FormControl
            v-model="importType"
            label="Import type"
            type="select"
            :options="[
              { label: 'Projects', value: 'projects' },
              { label: 'Sanctions', value: 'funding_sanctions' },
              { label: 'Funding revisions', value: 'funding_revisions' },
              { label: 'Tranches', value: 'tranches' },
            ]"
          />
          <label class="block">
            <span class="mb-1 block text-sm text-muted">CSV file</span>
            <input type="file" accept=".csv,text/csv" class="block w-full border border-line px-3 py-2 text-sm" @change="chooseFile" />
          </label>
          <Button label="Download template" icon-left="download" @click="exportFile(`/api/v1/imports/templates/${importType}.csv`, `${importType}-template.csv`)" />
          <Button variant="solid" label="Preview" icon-left="eye" :loading="loading" @click="preview" />
        </div>

        <div v-if="batch" class="mt-5 grid gap-3 md:grid-cols-5">
          <StatTile label="Rows" :value="batch.rowsDetected" />
          <StatTile label="Valid" :value="batch.validRows" tone="success" />
          <StatTile label="Invalid" :value="batch.invalidRows" :tone="batch.invalidRows ? 'danger' : 'default'" />
          <StatTile label="Duplicates" :value="batch.duplicateRows" />
          <StatTile label="Updates" :value="batch.proposedUpdates" />
        </div>

        <div v-if="batch" class="mt-5 flex justify-end">
          <Button variant="solid" label="Commit valid rows" icon-left="check" :disabled="batch.invalidRows > 0 || batch.status === 'committed'" :loading="loading" @click="commit" />
        </div>
      </section>

      <section class="border border-line bg-panel p-4">
        <h2 class="text-base font-semibold">Exports</h2>
        <div class="mt-4 grid gap-2">
          <Button label="Project master CSV" icon-left="download" @click="exportFile('/api/v1/exports/project-master.csv', 'project-master.csv')" />
          <Button label="Tranche register CSV" icon-left="download" @click="exportFile('/api/v1/exports/tranche-register.csv', 'tranche-register.csv')" />
          <Button label="Project master XLSX" icon-left="download" @click="exportFile('/api/v1/exports/project-master.xlsx', 'project-master.xlsx')" />
          <Button label="Tranche register XLSX" icon-left="download" @click="exportFile('/api/v1/exports/tranche-register.xlsx', 'tranche-register.xlsx')" />
        </div>
      </section>
    </div>

    <section v-if="batch" class="mt-5 overflow-x-auto border border-line bg-panel">
      <table class="min-w-full text-left text-sm">
        <thead class="border-b border-line bg-gray-50 text-xs uppercase text-muted">
          <tr>
            <th class="px-4 py-2">Row</th>
            <th class="px-4 py-2">Action</th>
            <th class="px-4 py-2">Status</th>
            <th class="px-4 py-2">Errors</th>
            <th class="px-4 py-2">Warnings</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in rows" :key="row.id" class="border-b border-line">
            <td class="px-4 py-3">{{ row.rowNumber }}</td>
            <td class="px-4 py-3">{{ labelize(row.proposedAction) }}</td>
            <td class="px-4 py-3"><Badge :label="labelize(row.status)" /></td>
            <td class="px-4 py-3 text-danger">{{ row.errors.join(', ') || '-' }}</td>
            <td class="px-4 py-3 text-muted">{{ row.warnings.join(', ') || '-' }}</td>
          </tr>
        </tbody>
      </table>
    </section>
  </AppShell>
</template>
